name: glife
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  intl: ^0.17.0


dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/logo.jpeg
    - assets/images/character.jpeg
    - assets/images/sunglasses.jpg
    - assets/images/character_sunglasses.png

